name: Contrabando de Chuva
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    permissions: # ISSO AQUI garante a permissão via código também
      contents: write
    steps:
      - uses: actions/checkout@v4 # Versão 4 é a mais atualizada
      
      - name: Baixando Imagem
        run: |
          # O link do RainViewer às vezes precisa de um "disfarce" (User-Agent)
          curl -L -A "Mozilla/5.0" "https://tilecache.rainviewer.com/v2/radar/nowcast_5/256/1/1/1/2/1_1.png" -o radar.png
          
      - name: Salvar no Repositório
        run: |
          git config --global user.name 'Robo do Clima'
          git config --global user.email 'bot@github.com'
          git add radar.png
          git commit -m "Chuva atualizada" || exit 0
          git push
