name: Contrabando de Chuva
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Instalar Dependencias
        run: pip install requests
        
      - name: Rodar Script de Download
        run: python baixar_radar.py
          
      - name: Salvar no Repositório
        run: |
          git config --global user.name 'Robo do Clima'
          git config --global user.email 'bot@github.com'
          git add radar.png
          git commit -m "Chuva atualizada" || exit 0
          git push
